# Generated by Django 5.2.10 on 2026-01-09 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'もう一度'), (2, '難しい'), (3, '良い'), (4, '簡単')], verbose_name='評価')),
                ('state', models.IntegerField(choices=[(0, '新規'), (1, '学習中'), (2, '復習'), (3, '再学習')], verbose_name='復習時の状態')),
                ('stability', models.FloatField(verbose_name='復習時の安定性')),
                ('difficulty', models.FloatField(verbose_name='復習時の難易度')),
                ('elapsed_days', models.FloatField(default=0, verbose_name='経過日数')),
                ('scheduled_days', models.FloatField(default=0, verbose_name='予定間隔（日）')),
                ('review_time', models.DateTimeField(auto_now_add=True, verbose_name='復習日時')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='回答時間(ms)')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='cards.card', verbose_name='カード')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '復習履歴',
                'verbose_name_plural': '復習履歴',
                'ordering': ['-review_time'],
            },
        ),
        migrations.CreateModel(
            name='CardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stability', models.FloatField(default=0.0, verbose_name='安定性')),
                ('difficulty', models.FloatField(default=0.0, verbose_name='難易度')),
                ('due', models.DateTimeField(default=django.utils.timezone.now, verbose_name='期限')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, verbose_name='次回復習日時')),
                ('last_review', models.DateTimeField(blank=True, null=True, verbose_name='最終復習日時')),
                ('state', models.IntegerField(choices=[(0, '新規'), (1, '学習中'), (2, '復習'), (3, '再学習')], default=0, verbose_name='状態')),
                ('reps', models.PositiveIntegerField(default=0, verbose_name='復習回数')),
                ('lapses', models.PositiveIntegerField(default=0, verbose_name='忘却回数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_states', to='cards.card', verbose_name='カード')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_states', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'カード状態',
                'verbose_name_plural': 'カード状態',
                'constraints': [models.UniqueConstraint(fields=('card', 'user'), name='unique_card_user_state')],
            },
        ),
    ]
