# Generated by Django 5.2.10 on 2026-01-09 04:01

import apps.cards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(verbose_name='表面（質問）')),
                ('back', models.TextField(verbose_name='裏面（答え）')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to=apps.cards.models.card_image_path, verbose_name='表面画像')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to=apps.cards.models.card_image_path, verbose_name='裏面画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck', verbose_name='デッキ')),
            ],
            options={
                'verbose_name': 'カード',
                'verbose_name_plural': 'カード',
                'ordering': ['-created_at'],
            },
        ),
    ]
